[package]
name = "ethereum-consensus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["serde", "async", "spec_tests"]
async = ["tokio", "tokio-stream", "async-stream"]
spec_tests = []

[dependencies]
ssz_rs = { git = "https://github.com/ralexstokes/ssz_rs" }
ssz_rs_derive = { git = "https://github.com/ralexstokes/ssz_rs" }
blst = "0.3.6"
rand = "0.8.4"
thiserror = "1.0.30"
sha2 = "0.9.8"
hex = "0.4.3"
integer-sqrt = "0.1.5"
enr = "0.5.1"
multiaddr = "0.14.0"
libp2p-core = { version = "0.32.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_yaml = "0.8"
glob = "0.3.0"

tokio = { version =  "1.18.2", features = ["full"], optional = true }
tokio-stream = { version = "0.1.8", optional = true }
async-stream = { version = "0.3.3", optional = true }

[dev-dependencies]
serde_json = "1.0.81"
