[package]
name = "ethereum_consensus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssz_rs = { git = "https://github.com/ralexstokes/ssz_rs" }
ssz_rs_derive = { git = "https://github.com/ralexstokes/ssz_rs" }
blst = "0.3.6"
rand = "0.8.4"
thiserror = "1.0.30"
sha2 = "0.9.8"
hex = "0.4.3"
