[package]
name = "ethereum-consensus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["default-without-bls", "bls"]
default-without-bls = ["serde", "async"]
bls = []
serde = ["dep:serde", "hex", "serde_json"]
async = ["tokio", "tokio-stream", "async-stream"]
spec-tests = ["serde", "serde_yaml"]
gen-spec = ["syn", "prettyplease", "quote"]
gen-tests = ["walkdir", "convert_case"]
peer-id = ["libp2p-core"]

[dependencies]
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs" }
blst = "0.3.6"
rand = "0.8.4"
thiserror = "1.0.30"
sha2 = "0.9.8"
integer-sqrt = "0.1.5"
enr = "0.5.1"
multiaddr = "0.14.0"

libp2p-core = { version = "0.32.1", features = ["serde"], optional = true }

serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0.81", optional = true }
serde_yaml = { version = "0.8", optional = true }
hex = {version = "0.4.3", optional = true }

tokio = { version =  "1.18.2", features = ["full"], optional = true }
tokio-stream = { version = "0.1.8", optional = true }
async-stream = { version = "0.3.3", optional = true }

syn = { version = "1.0.98", features = ["full", "visit", "visit-mut", "extra-traits"], optional = true }
prettyplease = { version = "0.1.10", optional = true }
quote = { version = "1.0.18", optional = true }

walkdir = { version = "2.3.2", optional = true }
convert_case = { version =  "0.5.0", optional = true }

[dev-dependencies]
serde_with = "1.13.0"
snap = "1"

[[bin]]
name = "gen-spec"
path = "src/bin/gen_spec.rs"
required-features = ["gen-spec"]

[[bin]]
name = "gen-tests"
path = "src/bin/gen_tests.rs"
required-features = ["gen-tests"]
